ENABLE_MULTI_ROUTE_EXPANSION = True
ENABLE_SECONDARY_EXPANSION = ENABLE_MULTI_ROUTE_EXPANSION
ENABLE_REDUNDANCY = False
ENABLE_DEFENSIVE_BUILDING = True
ENABLE_RAIDS = True
ENABLE_FORWARD_GUNNERS = True
ENABLE_LAUNCHERS = False
ENABLE_PHASE_STRATEGY = True
